name: Build and Release APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Decode and save keystore
        run: |
          printf "%s" "$KEYSTORE_BASE64" | tr -d '[:space:]' | base64 --decode > release.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Check keystore file
        run: |
          ls -l release.keystore
          file release.keystore

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Align APK
        run: |
          zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-aligned.apk

      - name: Sign APK
        run: |
          apksigner sign --ks release.keystore \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
            --out app/build/outputs/apk/release/app-release-signed.apk \
            app/build/outputs/apk/release/app-release-aligned.apk

      - name: Verify APK
        run: |
          apksigner verify app/build/outputs/apk/release/app-release-signed.apk

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release-signed.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
